version: '3'

services:
    ManagementCenter:
        image: "centerimage:latest"
        container_name: "managementcenter"
        restart: always
        build:
              context: ./ManagementCenter
        environment:
            - SENSOR_RECEIVER_PORT=5000
            - HTTP_SERVER_PORT=6000
        ports:
            - 6000:6000
    
    Sensor1:
        image: "sensorimage:latest"
        restart: always
        container_name: "sensor1"
        build:
              context: ./Sensor
        environment:
            - IP=managementcenter
            - PORT=5000
            - LOCATION=bathroom
            - SLEEPTIMER=5000

    Sensor2:
        image: "sensorimage:latest"
        restart: always
        container_name: "sensor2"
        build:
              context: ./Sensor
        environment:
            - IP=managementcenter
            - PORT=5000
            - LOCATION=kitchen
            - SLEEPTIMER=3000

    Sensor3:
        image: "sensorimage:latest"
        restart: always
        container_name: "sensor3"
        build:
              context: ./Sensor
        environment:
            - IP=managementcenter
            - PORT=5000
            - LOCATION=garden
            - SLEEPTIMER=6000

    Sensor4:
        image: "sensorimage:latest"
        restart: always
        container_name: "sensor4"
        build:
              context: ./Sensor
        environment:
            - IP=managementcenter
            - PORT=5000
            - LOCATION=bedroom
            - SLEEPTIMER=10000
