version: '3'

services:
    ManagementCenter:
        image: "centerimage:latest"
        container_name: "managementcenter"
        restart: always
        build:
              context: ./ManagementCenter
        environment:
            - SENSOR_RECEIVER_PORT=5000
            - HTTP_SERVER_PORT=7000
            - MQTT=1
            - Broker=mqttcontainer
            - Brokerport=1883
        ports:
            - 7000:7000
        depends_on:
            - MOSQUITTO

    Sensor1:
        image: "sensorimage:latest"
        restart: always
        container_name: "sensor1"
        build:
              context: ./Sensor
        environment:
            - IP=managementcenter
            - PORT=5000
            - LOCATION=bathroom
            - SLEEPTIMER=5000
            - MQTT=1
            - Broker=mqttcontainer
            - Brokerport=1883
        depends_on:
            - ManagementCenter

    Sensor2:
        image: "sensorimage:latest"
        restart: always
        container_name: "sensor2"
        build:
              context: ./Sensor
        environment:
            - IP=managementcenter
            - PORT=5000
            - LOCATION=kitchen
            - SLEEPTIMER=4000
            - MQTT=1
            - Broker=mqttcontainer
            - Brokerport=1883
        depends_on:
            - ManagementCenter

    Sensor3:
        image: "sensorimage:latest"
        restart: always
        container_name: "sensor3"
        build:
              context: ./Sensor
        environment:
            - IP=managementcenter
            - PORT=5000
            - LOCATION=garden
            - SLEEPTIMER=6000
            - MQTT=1
            - Broker=mqttcontainer
            - Brokerport=1883
        depends_on:
            - ManagementCenter
    Sensor4:
        image: "sensorimage:latest"
        restart: always
        container_name: "sensor4"
        build:
              context: ./Sensor
        environment:
            - IP=managementcenter
            - PORT=5000
            - LOCATION=bedroom
            - SLEEPTIMER=10000
            - MQTT=1
            - Broker=mqttcontainer
            - Brokerport=1883
        depends_on:
            - ManagementCenter
    MOSQUITTO:
        image: eclipse-mosquitto:2.0.11
        restart: always
        container_name: "mqttcontainer"
        command: mosquitto -c /mosquitto-no-auth.conf



